#macro VIEW 0
#macro VIEW_CAM view_camera[VIEW]
#macro VIEW_WIDTH 640
#macro VIEW_HEIGHT 360
#macro VIEW_SCALE 2

#macro GUI_WIDTH VIEW_WIDTH
#macro GUI_HEIGHT VIEW_HEIGHT

#macro WINDOW_TITLE "Astars"
#macro WINDOW_WIDTH VIEW_WIDTH * VIEW_SCALE
#macro WINDOW_HEIGHT VIEW_HEIGHT * VIEW_SCALE

#macro CELL_SIZE 32