#macro VIEW 0
#macro VIEW_CAM view_camera[VIEW]
#macro VIEW_WIDTH 480
#macro VIEW_HEIGHT 270
#macro VIEW_SCALE 2

#macro GUI_WIDTH VIEW_WIDTH
#macro GUI_HEIGHT VIEW_HEIGHT

#macro WINDOW_TITLE "Astars"
#macro WINDOW_WIDTH VIEW_WIDTH * VIEW_SCALE
#macro WINDOW_HEIGHT VIEW_HEIGHT * VIEW_SCALE

#macro DEBUG_MODE true
#macro CELL_SIZE 32